import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Header/Navbar";
import CustomApolloProvider from "@/components/CustomApolloProvider";
import { Toaster } from "react-hot-toast";
import { cookies } from "next/headers";
import { UserProvider } from "@/context/userContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Todo : Improve the metadata later on...
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("accessToken");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CustomApolloProvider>
          <UserProvider token={token?.value ?? undefined}>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              disableTransitionOnChange>
              <Navbar />
              {children}
              <Toaster position="top-center" />
            </ThemeProvider>
          </UserProvider>
        </CustomApolloProvider>
      </body>
    </html>
  );
}
